# Generated by Django 4.2.7 on 2023-11-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='превью(картинка)')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='превью(картинка)')),
                ('link', models.SlugField(blank=True, max_length=200, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField(auto_now_add=True, verbose_name='дата оплаты')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма оплаты')),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Transfer', 'Transfer')], default='Card', max_length=255, verbose_name='способы оплаты')),
                ('course_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course')),
                ('lesson_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lesson')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('date_of_payment',),
            },
        ),
    ]
