# Generated by Django 4.2.7 on 2023-12-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='цена'),
        ),
    ]
